### ISSUE TITLE
User Story: README.md

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/Predictive-Analytics-PP5#7]
As a **Project Developer** I would like **to clearly document the project** so that **other users can understand it's purpose, the setup process, and how to use or contribute to the project**.

## Acceptance Criteria
- Mardown formatting should be clean and consistent for readability.
- All sections are completed (see tasks) in full.
- All links work and all media appears as expected.

## Tasks
- [x] Introduction
- [x] Table of Contents
- [x] Dataset Contents
- [x] Business Requirements
- [x] Hypothesis & How to Validate
- [x] Rationale to Map Business Requirements to the Data Visualizations and ML Tasks
- [x] Machine Learning Business Case
- [x] User Stories
- [x] Dashboard Design
- [x] Methodology
- [x] Rationale for the Model
- [x] Project Features
- [x] Project Outcomes
- [x] Hypothesis Outcomes
- [x] Testing
- [x] Deployment
- [x] Main Data Analysis in ML Libraries
- [x] Credits
